### ISSUE TITLE
add-aggregator not working

### ISSUE THREAD

**Issue by dafyddd** [octopus-network/solana-flux-aggregator#10]
I'm having issues deploying a new aggregator using the instructions in the README.

```
dd@dd-p53:~/solana-flux-aggregator$ yarn solink add-aggregator --feedName btc:usd --submitInterval 6 --minSubmissionValue 0 --maxSubmissionValue 18446744073709551615
yarn run v1.22.5
$ ts-node src/cli.ts add-aggregator --feedName btc:usd --submitInterval 6 --minSubmissionValue 0 --maxSubmissionValue 18446744073709551615
Transaction simulation failed: Error processing Instruction 1: invalid instruction data 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program F3W3N9iZy3ZLZkYFUFRmGPVneBrHoE6gveVyjPPqn825 invoke [1]
    Program log: Error: InvalidInstructionData
    Program F3W3N9iZy3ZLZkYFUFRmGPVneBrHoE6gveVyjPPqn825 consumed 1839 of 200000 compute units
    Program F3W3N9iZy3ZLZkYFUFRmGPVneBrHoE6gveVyjPPqn825 failed: invalid instruction data
(node:128389) UnhandledPromiseRejectionWarning: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: invalid instruction data
    at Connection._callee53$ (/home/dd/solana-flux-aggregator/node_modules/solray/node_modules/@solana/web3.js/src/connection.js:2957:13)
    at tryCatch (/home/dd/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/dd/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/dd/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/dd/solana-flux-aggregator/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/dd/solana-flux-aggregator/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:128389) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:128389) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by czl1378** [comment]
Sorry my mistake, I've added "decimals" to aggregator but forgot to update the cli.
