### ISSUE TITLE
Unable to deploy program

### ISSUE THREAD

**Issue by PatrickAlphaC** [octopus-network/solana-flux-aggregator#11]
Following the readme verbatim, I run into this error:

On the command: `yarn solink deploy-program`

```
patrick@iMac: [~/code/solana-chainlink/solana-flux-aggregator -  (master)] $ yarn solink deploy-program
yarn run v1.22.10
$ ts-node src/cli.ts deploy-program
deploying /Users/patrick/code/solana-chainlink/solana-flux-aggregator/build/flux_aggregator.so...
(node:53116) UnhandledPromiseRejectionWarning: Error: Transaction was not confirmed in 10.01 seconds
    at Connection._callee20$ (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/solray/node_modules/@solana/web3.js/src/connection.js:2227:13)
    at tryCatch (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/patrick/code/solana-chainlink/solana-flux-aggregator/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
(node:53116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 13.94s.
```

OS: MacOS BigSur 
Node: 12.20.0, 14.15.2
npm: 6.14.9
rustup: 1.23.1
solana-cli: 1.5.2

**Comment by czl1378** [comment]
Maybe you should try again, sometimes this happens. 

By the way, I just fixed an issue, you may want to pull the remote changes.

**Comment by PatrickAlphaC** [comment]
This is fixed
