### ISSUE TITLE
can't build project locally due to missing type decls

### ISSUE THREAD

**Issue by mschneider** [octopus-network/solana-flux-aggregator#2]
I get this error, after running `yarn install` in a clean checkout:

```
$ yarn solink generate-wallet

yarn run v1.22.10
$ ts-node src/cli.ts generate-wallet

/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/cli.ts:9:8 - error TS2307: Cannot find module 'solray' or its corresponding type declarations.

9 } from "solray"
         ~~~~~~~~

    at createTSError (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/max/Code/solana/solana-flux-aggregator/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by czl1378** [comment]
Sorry. Because solray is currently WIP, you can try to install via yarn 2.0. 

Alternatively, you can pull the new code I just pushed. Thanks for your feedback :)

**Comment by dafyddd** [comment]
I pulled fresh and I was able to get the program to compile and deploy to devnet. But when I try to initialize the aggregator I get this error:
```
dd@dd-p53:~/solana-flux-aggregator$ yarn solink add-aggregator --feedName btc:usd --submitInterval 6 --minSubmissionValue 0 --maxSubmissionValue 18446744073709551615
yarn run v1.22.5
$ ts-node src/cli.ts add-aggregator --feedName btc:usd --submitInterval 6 --minSubmissionValue 0 --maxSubmissionValue 18446744073709551615
(node:331364) UnhandledPromiseRejectionWarning: TypeError: buf.writeBigUInt64LE is not a function
    at Object.u64LEBuffer (/home/dd/solana-flux-aggregator/node_modules/solray/lib/util/encoding.js:48:9)
    at FluxAggregator.initializeInstruction (/home/dd/solana-flux-aggregator/src/FluxAggregator.ts:163:27)
    at FluxAggregator.initialize (/home/dd/solana-flux-aggregator/src/FluxAggregator.ts:127:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:331364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:331364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mschneider** [comment]
Thank you for your help.
